name: Use JSON Secret

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get JSON secret
      id: get_json
      run: echo "${{ secrets.HOTEL_DOMAINS }}" > hotel_domains.json

    - name: Parse JSON and use in script
      run: |
        # Install jq to parse JSON
        sudo apt-get install -y jq
        
        # Read JSON and use in script
        DOMAIN_LIST=$(cat hotel_domains.json | jq -r '.[]')
        
        echo "Domains:"
        for domain in $DOMAIN_LIST; do
          echo " - $domain"
        done